# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: |
      bash patch.sh
      sudo kill -9 $(ps -fA | grep 'sh /ide' | head -n1 | awk '{print $2}')
