# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: |
      bash patch.sh
      gp ports await 23000 1>/dev/null
      for pid in $(ps -fA | grep '[s]h /ide/bin/gitpod-code' | awk '{print $2}'); do {
        sudo kill -9 $pid
      } done
      ps -fA > process.log
